// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HelloStreamRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloStreamRequest) Reset()         { *m = HelloStreamRequest{} }
func (m *HelloStreamRequest) String() string { return proto.CompactTextString(m) }
func (*HelloStreamRequest) ProtoMessage()    {}
func (*HelloStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *HelloStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloStreamRequest.Unmarshal(m, b)
}
func (m *HelloStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloStreamRequest.Marshal(b, m, deterministic)
}
func (m *HelloStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloStreamRequest.Merge(m, src)
}
func (m *HelloStreamRequest) XXX_Size() int {
	return xxx_messageInfo_HelloStreamRequest.Size(m)
}
func (m *HelloStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloStreamRequest proto.InternalMessageInfo

func (m *HelloStreamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloStreamResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloStreamResponse) Reset()         { *m = HelloStreamResponse{} }
func (m *HelloStreamResponse) String() string { return proto.CompactTextString(m) }
func (*HelloStreamResponse) ProtoMessage()    {}
func (*HelloStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *HelloStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloStreamResponse.Unmarshal(m, b)
}
func (m *HelloStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloStreamResponse.Marshal(b, m, deterministic)
}
func (m *HelloStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloStreamResponse.Merge(m, src)
}
func (m *HelloStreamResponse) XXX_Size() int {
	return xxx_messageInfo_HelloStreamResponse.Size(m)
}
func (m *HelloStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloStreamResponse proto.InternalMessageInfo

func (m *HelloStreamResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
	proto.RegisterType((*HelloStreamRequest)(nil), "HelloStreamRequest")
	proto.RegisterType((*HelloStreamResponse)(nil), "HelloStreamResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe2, 0xe2, 0xf1, 0x48, 0xcd, 0xc9, 0xc9, 0x0f, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x34, 0xb9, 0x78, 0xa1, 0x6a, 0x8a, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x61, 0xea, 0x60, 0x5c,
	0x25, 0x0d, 0x2e, 0x21, 0xb0, 0xd2, 0xe0, 0x92, 0xa2, 0xd4, 0xc4, 0x5c, 0x7c, 0x86, 0xea, 0x73,
	0x09, 0xa3, 0xa8, 0x24, 0x64, 0xb4, 0x51, 0x2e, 0x17, 0xb3, 0x63, 0x41, 0xa6, 0x90, 0x06, 0x17,
	0x2b, 0x58, 0x9f, 0x10, 0xaf, 0x1e, 0xb2, 0xc3, 0xa5, 0xf8, 0xf4, 0x50, 0xdc, 0xa8, 0xc4, 0x20,
	0x64, 0xc3, 0xc5, 0x8d, 0x64, 0x83, 0x90, 0xb0, 0x1e, 0xa6, 0xcb, 0xa4, 0x44, 0xf4, 0xb0, 0x38,
	0x42, 0x89, 0xc1, 0x80, 0x31, 0x89, 0x0d, 0x1c, 0x3e, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x60, 0xba, 0x24, 0x12, 0x2c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	HelloStream(ctx context.Context, in *HelloStreamRequest, opts ...grpc.CallOption) (Api_HelloStreamClient, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/Api/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) HelloStream(ctx context.Context, in *HelloStreamRequest, opts ...grpc.CallOption) (Api_HelloStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Api_serviceDesc.Streams[0], "/Api/HelloStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiHelloStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_HelloStreamClient interface {
	Recv() (*HelloStreamResponse, error)
	grpc.ClientStream
}

type apiHelloStreamClient struct {
	grpc.ClientStream
}

func (x *apiHelloStreamClient) Recv() (*HelloStreamResponse, error) {
	m := new(HelloStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	HelloStream(*HelloStreamRequest, Api_HelloStreamServer) error
}

// UnimplementedApiServer can be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (*UnimplementedApiServer) Hello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (*UnimplementedApiServer) HelloStream(req *HelloStreamRequest, srv Api_HelloStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method HelloStream not implemented")
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Api/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_HelloStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).HelloStream(m, &apiHelloStreamServer{stream})
}

type Api_HelloStreamServer interface {
	Send(*HelloStreamResponse) error
	grpc.ServerStream
}

type apiHelloStreamServer struct {
	grpc.ServerStream
}

func (x *apiHelloStreamServer) Send(m *HelloStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Api_Hello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HelloStream",
			Handler:       _Api_HelloStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
